
# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [3]:
# your code goes here
array1=np.zeros(10)
print(array1)
array1.size

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10



### Create a numpy array with values ranging from 10 to 49

In [4]:
# your code goes here
array2=np.arange(10,49)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]




### Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
# your code goes here
array3=np.ones((2,2),dtype=int)
print(array3)
print(type(array3))

[[1 1]
 [1 1]]
<class 'numpy.ndarray'>




### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
# your code goes here
array4=np.ones((3,2),dtype=float)
print(array4)
print(type(array4))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>




### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
# your code goes here
X=np.array([[2,4,5],[6,7,0]])
Y=np.full_like(X, 1)
print("X=",X)
print("Y=",Y)

X= [[2 4 5]
 [6 7 0]]
Y= [[1 1 1]
 [1 1 1]]




### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [8]:
# your code goes here
X=np.array([[2,4,5],[6,7,0]])
Y=np.full_like(X, 0)
print("X=",X)
print("Y=",Y)

X= [[2 4 5]
 [6 7 0]]
Y= [[0 0 0]
 [0 0 0]]




### Create a numpy matrix of 4*4 integers, filled with fives.

In [9]:
# your code goes here
X=np.full((4,4),5)
print(X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]




### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [10]:
# your code goes here
X=np.array([[2,4,5],[6,7,0]])
Y=np.full_like(X, 7)
print("X=",X)
print("Y=",Y)

X= [[2 4 5]
 [6 7 0]]
Y= [[7 7 7]
 [7 7 7]]




### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [11]:
# your code goes here
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [12]:
# your code goes here
x=np.random.randint(1,10,3)
print(x)

[5 4 9]




### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [13]:
# your code goes here
x=np.random.random((3,3,3))
print(x)

[[[0.36748045 0.6729175  0.42276104]
  [0.34251453 0.86283716 0.54272131]
  [0.80013443 0.83446169 0.53995025]]

 [[0.80101209 0.11371117 0.29005147]
  [0.90010127 0.07632582 0.91086304]
  [0.83469103 0.1698564  0.2852566 ]]

 [[0.5968723  0.18055956 0.33355393]
  [0.91345979 0.68637667 0.36667448]
  [0.52128369 0.97966944 0.70873206]]]




### Given the X python list convert it to an Y numpy array

In [14]:
# your code goes here
X=[1,4,7]
Y=np.array(X)
print(Y)

[1 4 7]




### Given the X numpy array, make a copy and store it on Y.

In [15]:
# your code goes here
X=np.array([[2,4,5],[6,7,0]])
Y=np.copy(X)
print(Y)

[[2 4 5]
 [6 7 0]]




### Create a numpy array with numbers from 1 to 10

In [16]:
# your code goes here
X=np.arange(1,10)
print(X)

[1 2 3 4 5 6 7 8 9]




### Create a numpy array with the odd numbers between 1 to 10

In [17]:
# your code goes here
X=np.arange(1,10,2)

print(X)

[1 3 5 7 9]




### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [18]:
# your code goes here
X=np.arange(9)
Y=X.reshape(3,3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]




### Show the memory size of the given Z numpy matrix

In [19]:
# your code goes here
Z=np.array([[1,3,6],[1,9,0]])
print(Z)
print(Z.itemsize *Z.size)

[[1 3 6]
 [1 9 0]]
48


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [20]:
# your code goes here
x=np.array([[1,2,3],[4,5,6]])
print(x[0,0])

1




### Given the X numpy array, show it's last element

In [21]:
# your code goes here
x=np.array([[1,2,3],[4,5,6]])
print(x[-1,-1])

6




### Given the X numpy array, show it's first three elements

In [22]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
print(x[0,:3])

[1 2 3]




### Create a numpy array with numbers from 1 to 10, in descending order.

In [23]:
# your code goes here
x=np.random.randint(1,10,9)
y=np.sort(x)[::-1]
print(x)
print(y)

[4 2 8 3 3 9 3 3 1]
[9 8 4 3 3 3 3 2 1]




### Given the X numpy array, show all middle elements

In [24]:
# your code goes here




### Given the X numpy array, show the elements in reverse position

In [25]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
reversed_arr = x[::-1]
print(reversed_arr )

[[4 5 6 7 8 9]
 [1 2 3 2 5 6]]




### Given the X numpy array, show the elements in an odd position

In [61]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
y=x%2!=0
print(x[y])

[1 3 5 5 7 9]




### Given the X numpy matrix, show the first row elements

In [63]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
print(x[0])

[1 2 3 2 5 6]




### Given the X numpy matrix, show the last row elements

In [64]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
print(x[-1])

[4 5 6 7 8 9]




### Given the X numpy matrix, show the first element on first row

In [66]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
print(x[0,0])

1




### Given the X numpy matrix, show the last element on last row

In [67]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
print(x[-1,-1])

9




### Given the X numpy matrix, show the middle row elements

In [31]:
# your code goes here




### Given the X numpy matrix, show the first two elements on the first two rows

In [70]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9],[2,5,6,7,8,9]])
print(x[:2,:2])

[[1 2]
 [4 5]]




### Given the X numpy matrix, show the last two elements on the last two rows

In [72]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9],[2,5,6,7,8,10]])
print(x[-2:,-2:])

[[ 8  9]
 [ 8 10]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [34]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
y=np.array(x,float)
print(y)

[[1. 2. 3. 2. 5. 6.]
 [4. 5. 6. 7. 8. 9.]]




### Reverse the given numpy array (first element becomes last)

In [35]:
# your code goes here





### Order (sort) the given numpy array

In [36]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9]])
y=np.sort(x)
print(y)


[[1 2 2 3 5 6]
 [4 5 6 7 8 9]]




### Given the X numpy array, set the fifth element equal to 1

In [37]:
# your code goes here
x=np.array([1,2,3,2,5,6])
x[4]=1
print(x)

[1 2 3 2 1 6]




### Given the X numpy array, change the 50 with a 40

In [74]:
# your code goes here
x=np.array([1,2,3,2,50,6])
x[x==50]=40
print(x)

[ 1  2  3  2 40  6]



### Given the X numpy matrix, change the last row with all 1

In [75]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9],[2,5,6,7,8,10]])
x[-1]=1
print(x)

[[1 2 3 2 5 6]
 [4 5 6 7 8 9]
 [1 1 1 1 1 1]]



### Given the X numpy matrix, change the last item on the last row with a 0

In [77]:
# your code goes here
x=np.array([[1,2,3,2,5,6],[4,5,6,7,8,9],[2,5,6,7,8,10]])
x[-1,-1]=0
print(x)

[[1 2 3 2 5 6]
 [4 5 6 7 8 9]
 [2 5 6 7 8 0]]



### Given the X numpy matrix, add 5 to every element

In [41]:
# your code goes here
x=np.array([1,2,3,2,5,6])+5
print(x)

[ 6  7  8  7 10 11]



## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [42]:
# your code goes here
x=np.array([1,-2,3,2,-5])
import numpy.ma as ma
y = ma.masked_array(x, mask=[0,1,0,0,1])
print(y)


[1 -- 3 2 --]



### Given the X numpy array, get the negative elements

In [43]:
# your code goes here
x=np.array([[1,-2,3,2,-5,6],[-4,5,6,7,8,-9]])

filter_arr = x<0

newarr = x[filter_arr]
print(newarr)

[-2 -5 -4 -9]



### Given the X numpy array, get numbers higher than 5

In [44]:
# your code goes here
x=np.array([[1,-2,3,2,-5,6],[-4,5,6,7,8,-9]])

filter_arr = x>5

newarr = x[filter_arr]
print(newarr)

[6 6 7 8]



### Given the X numpy array, get numbers higher than the elements mean

In [45]:
# your code goes here
x=np.array([[1,-2,3,2,-5,6],[-4,5,6,7,8,-9]])
m=np.mean(x)
print(m)
filter_arr = x>m

newarr = x[filter_arr]
print(newarr)

1.5
[3 2 6 5 6 7 8]



### Given the X numpy array, get numbers equal to 2 or 10

In [46]:
# your code goes here
x=np.array([[1,-2,3,2,-5,6],[-4,5,6,7,8,-9]])
y = x[x==2]
print(x[x==2],x[x==10])

[2] []



## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [47]:
# your code goes here
x=np.array([[1,-2,3,2,-5,6],[-4,5,1,7,8,-9]]).all()
y=x!=0
print(y)

True



## Summary statistics

### Given the X numpy array, show the sum of its elements

In [48]:
# your code goes here
x=np.array([[1,0,3,2,0,0],[0,5,1,0,0,0]])
print(x.sum())

12



### Given the X numpy array, show the mean value of its elements

In [49]:
# your code goes here
x=np.array([[1,0,3,2,0,0],[0,5,1,0,0,0]])
print(x.mean())

1.0



### Given the X numpy matrix, show the sum of its columns

In [50]:
# your code goes here
x=np.array([[1,0,3,2,0,0],[0,11,1,0,0,0]])
print(x)
y=x.mean(axis=0)
print(y)

[[ 1  0  3  2  0  0]
 [ 0 11  1  0  0  0]]
[0.5 5.5 2.  1.  0.  0. ]



### Given the X numpy matrix, show the mean value of its rows

In [51]:
# your code goes here
x=np.array([[1,0,3,2,0,0],[0,11,1,0,0,0]])
print(x)
y=x.mean(axis=1)
print(y)

[[ 1  0  3  2  0  0]
 [ 0 11  1  0  0  0]]
[1. 2.]


### Given the X numpy array, show the max value of its elements

In [52]:
x=np.array([[1,0,3,2,0,0],[0,11,1,0,0,0]])
print(x.max())

11


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



# Answer The following questions!

In [53]:
# your code goes here
import seaborn as sns

In [54]:
df=sns.get_dataset_names()
df

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [55]:
import pandas as pd
df1=pd.DataFrame(df)
df1.head(20)

0
0         anagrams
1         anscombe
2        attention
3   brain_networks
4      car_crashes
5         diamonds
6             dots
7         exercise
8          flights
9             fmri
10          gammas
11          geyser
12            iris
13             mpg
14        penguins
15         planets
16            tips
17         titanic

In [56]:
data= sns.load_dataset('titanic')
data

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

# Average age of woman category.

In [57]:
data[data.who=='woman'].age.mean()

32.0

## Average age of man category.

In [58]:
data[data.who=='man'].age.mean()

33.17312348668281

## The lowest age among alone woman.

In [59]:
data[data.who=='woman'].age.min()

16.0

# The highest pulse among running student and not fat category. 

# Sort the DataFrame in ascending order of the 'age' use sort values (df.sort_values(by='...', ascending=...)). 

In [60]:
y=data.sort_values(by=['age'],ascending=True)
y

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
803         1       3    male  0.42  ...   NaN    Cherbourg    yes  False
755         1       2    male  0.67  ...   NaN  Southampton    yes  False
644         1       3  female  0.75  ...   NaN    Cherbourg    yes  False
469         1       3  female  0.75  ...   NaN    Cherbourg    yes  False
78          1       2    male  0.83  ...   NaN  Southampton    yes  False
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
859         0       3    male   NaN  ...   NaN    Cherbourg     no   True
863         0       3  female   NaN  ...   NaN  Southampton     no  False
868         0       3    male   NaN  ...   NaN  Southampton     no   True
878         0       3    male   NaN  ...   NaN  Southampton     no   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False

[891 rows x 15 columns]